[versions]
paper = "1.21.4-R0.1-SNAPSHOT"
commandapi = "10.0.0"
axios = "1.1"
venturechat = "3.6.0"
carbon = "3.0.0-beta.27"
adventure = "4.17.0"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
commandapi-shade = { module = "dev.jorel:commandapi-bukkit-shade-mojang-mapped", version.ref = "commandapi" }
axios = { module = "software.axios:api", version.ref = "axios" }
venturechat = { group = "mineverse.Aust1n46.chat", name = "VentureChat", version.ref = "venturechat" }
carbon = { module = "de.hexaoxi:carbonchat-api", version.ref = "carbon" }
adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }
minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }